/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function compileAsync(code: string, globals: string): Promise<CostModel>
export class CostModel {
  costAsync(query: string, variables?: string | undefined | null): Promise<string>
}
